### ISSUE TITLE
Identify tangible and Intangible benifits

### ISSUE THREAD

**Issue by MoazJalal** [MoazJalal/Group3_Project1_SAD_20232024#6]

**Comment by Loaialqadasi** [comment]
The proposed system was to enhanced the experience of the passenger transportation in Johor Bahru. In order to improve the living cost saving and time saving for the residences.
Starting with the tangible benefits:

•	Visual Hierarchy: Arrange elements on the screen to guide users' attention. Prioritize critical information like bus schedules, delays, and estimated arrival times.

•	Clear Navigation: Ensure users can easily move between different screens or sections. Use intuitive icons or labels for navigation buttons.

Intangible benefits:

•	User Mental Models: Design screens based on users' expectations. Follow established
Conventions.
•	Efficiency: Aim for simplicity and transparency. Avoid overwhelming users with too many options.

•	Real-time data feed of bus locations and schedules. 

o	Frequency: Update the bus locations at regular intervals every few seconds to ensure real-time accuracy.

o	Estimated Arrival Times: Calculate and display estimated arrival times for upcoming buses at specific stops
